server:
  port: 8761

spring:
  application:
    name: SERVICE-REGISTRY
  jackson:
    default-property-inclusion: NON_EMPTY
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
