server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/advatix/team-3.git
          username: goyalankush
          password: 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
          clone-on-start: true
          search-paths: Backend Microservices/cloud-config-server/config-server
