apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-tls
  namespace: my-namespace
type: kubernetes.io/tls
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: my-namespace
spec:
  tls:
    - hosts:
      - myapp.com
      serviceName: myapp-secret-tls
  rules:
  - host: myapp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: mongo-express-service
          servicePort: 8082
      - path: /mongo-express
        backend:
          serviceName: mongo-express-service
          servicePort: 8082
