apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-external-express
  labels:
    app: mongo-external-express
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-external-express
  template:
    metadata:
      labels:
        app: mongo-external-express
    spec:
      containers:
      - name: mongo-external-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-external-express-service
  namespace: my-namespace
spec:
  selector:
    app: mongo-external-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000