server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  jackson:
    default-property-inclusion: NON_EMPTY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:            - name: CircuitBreaker
              args:                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
          order: 0
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: ACCOUNT-SERVICE
                fallbackuri: forward:/customerServiceFallBack
          order: 1
        - id: EMAIL-SERVICE
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/api/email/**
          filters:
            - name: CircuitBreaker
              args:
                name: EMAIL-SERVICE
                fallbackuri: forward:/emailServiceFallBack
          order: 2

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000

          
management:  endpoints:    web:      exposure:        include: hystrix.stream

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost


